### ISSUE TITLE
기후 데이터 저장

### ISSUE THREAD

**Issue by Icecoff22** [K-paas-issa/backend#1]
- [x] 3시간 주기로 기후 데이터를 저장한다.
- [x] 기후 데이터는 no sql에 저장한다.
- [x] 데이터는 기상청에서 제공하는 공공 데이터 API를 활용해 가져온다.
- [x] 가져오는 데이터는 풍향, 풍속, 기압 데이터이다.

**Comment by namest504** [comment]
좀 더 작업이 필요하지만 여태 작업한 내용 Push 올렸습니다.

[작업 내용]
1. 기존 코드 리팩토링 진행했습니다. (추가 작업 필요)
2. 문자열 가공 과정에서 공백 부분을 값으로 인식하는 문제 원인인 단순 " " Space 처리 과정을 정규식과 trim() 으로 가공하도록 수정하였습니다.
3. 외부 API 요청수가 많아 해당 부분에서 Heap 메모리 용량 초과하는 문제 해결했습니다. (기존 JVM 메모리 8GB 이상 사용 1시간 걸리는 과정 -> JVM 메모리 2GB사용 약 13분으로 단축)
4. mongoDB에 데이터 저장하는 기능 추가했습니다. (임시 처리)
5. 개발용 API  추가했습니다.

[추가 작업 내용]
1. cloud 서비스 활용해서 서버 인프라 구성 및 배포 flow 작성
2. batch를 통한 청크 단위 데이터 write 작업
3. 비즈니스 로직 분리 등 리팩토링 추가 과정 필요
4. 요청 API 결과 DB 저장 전 메소드 효율 향상 필요 (해당 부분에서 오래걸림)

[중요]
1. API 요청 키값 환경 변수로 변경 필요합니다.
